### ISSUE TITLE
tip

### ISSUE THREAD

**Issue by yohai** [nirzaa/yohai_nir_repo#7]
The git commands shouldn't really be in this repo, but it doesn't matter too much.
In any case, even if you want to keep it, I would recommend against `.lyx` format because of two reasons:

1. git and similar source-control programs rely on text deltas so changes in pdf files (which are binary files) are very cumbersome to keep track of.
2. `.lyx` has a lot of extra boilerplate code which is completely useless and sometimes very small changes in the actual output (the pdf) need a lot of changes in the code.

A better alternative is markdown, which is better because:
1. It allows almost the same flexibility: sections, lists, [links](https://www.youtube.com/watch?v=dQw4w9WgXcQ),  formatting `as code`, **text** _styles_ and so on. Math is more complicated but also possible if I remember correctly. 
2. It is pure text and therefore easy to keep track of using git (or its alternatives)
3. It renders automatically on github (like the message you are reading just now).

**Comment by nirzaa** [comment]
Updated. @yohai
